analyze_profile:
  description: >
    Analyze student data to determine skills, gaps, and strengths.
  expected_output: >
    JSON summarizing strengths, weaknesses, and areas needing improvement.
  agent: profile_analyzer

create_roadmap:
  description: >
    Generate a detailed semester-wise roadmap tailored to the student's curriculum, skill gaps, and dream companies' requirements.
  expected_output: >
    JSON structured roadmap divided semester-wise, including required extra skills.
  agent: roadmap_creator

curate_resources:
  description: >
    Curate recommended resources for each roadmap topic.
  expected_output: >
    JSON roadmap enriched with recommended resources (videos, blogs, projects, practice questions).
  agent: resource_curator
