analyze_profile:
  description: >
    Conduct a detailed analysis of the user's career profile, including skills, certifications, and experience.
    Identify key strengths, weaknesses, and areas for improvement.
  expected_output: >
    A comprehensive markdown report summarizing the user's profile analysis, highlighting skill gaps and opportunities.
  agent: profile_analyzer

create_roadmap:
  description: >
    Generate a personalized learning roadmap with clear milestones to help the user achieve their career goals.
    Include curated resources tailored to the user's profile.
  expected_output: >
    A roadmap document with milestones, timelines, and suggested resources for each stage of the learning journey.
  agent: roadmap_creator

career_guidance:
  description: >
    Provide actionable career advice based on the user's profile analysis and learning roadmap.
    Offer recommendations for certifications, projects, or experiences to enhance their career prospects.
  expected_output: >
    A markdown document containing personalized career advice, recommended next steps, and curated resources.
  agent: career_advisor
  output_file: career_guidance.md
